// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `diagnostics_pipeline_check`, `failed`, `ok`, `run_sqlite_probe`, `run_tree_sitter_cpp_probe`, `sqlite_check`, `tree_sitter_cpp_check`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

List<DiagnosticCheck> runStartupDiagnostics() =>
    RustLib.instance.api.crateApiDiagnosticsRunStartupDiagnostics();

class DiagnosticCheck {
  final String tool;
  final DiagnosticStatus status;
  final String? path;
  final String? message;

  const DiagnosticCheck({
    required this.tool,
    required this.status,
    this.path,
    this.message,
  });

  Future<String> line() =>
      RustLib.instance.api.crateApiDiagnosticsDiagnosticCheckLine(that: this);

  @override
  int get hashCode =>
      tool.hashCode ^ status.hashCode ^ path.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiagnosticCheck &&
          runtimeType == other.runtimeType &&
          tool == other.tool &&
          status == other.status &&
          path == other.path &&
          message == other.message;
}

enum DiagnosticStatus { ok, failed }
