import 'dart:io';

/// Regenerates the permanent screenshot gallery
/// (`docs/screenshots/README.md`) from the PNGs the widget-test screenshot
/// suite (`test/screenshots/`) captured into `sourceDir`, so GitHub renders
/// them inline — no GitHub Pages, no build step on the viewer's side.
Future<void> main(List<String> args) async {
  if (args.length != 2) {
    stderr.writeln(
      'usage: dart run tool/generate_screenshot_gallery.dart '
      '<screenshots-source-dir> <gallery-output-dir>',
    );
    exitCode = 64;
    return;
  }

  final sourceDir = Directory(args[0]);
  final outputDir = Directory(args[1]);
  await outputDir.create(recursive: true);

  final pngFiles =
      sourceDir
          .listSync()
          .whereType<File>()
          .where((file) => file.path.endsWith('.png'))
          .toList()
        ..sort((a, b) => _baseName(a.path).compareTo(_baseName(b.path)));

  for (final file in pngFiles) {
    final name = _baseName(file.path);
    await file.copy('${outputDir.path}/$name');
  }

  final markdown = buildGalleryMarkdown(
    pngFiles.map((file) => _baseName(file.path)).toList(),
  );
  await File('${outputDir.path}/README.md').writeAsString(markdown);
}

String _baseName(String path) => path.split(Platform.pathSeparator).last;

/// US titles as they appear in `docs/plans/User Steps.md`, the single
/// source of truth for what each US covers.
const _groupTitles = {
  'us1': 'US-1 — Criação de projeto e ingestão do input',
  'us2': 'US-2 — Lista de arquivos fonte e leitura de conteúdo',
  'us3': 'US-3 — Catálogo de tipos do projeto',
  'us4': 'US-4 — Usos de cada tipo e navegação',
  'us5': 'US-5 — Funções, métodos e macros, e seus usos',
};

final _groupPrefix = RegExp(r'^(us\d+)-');

/// Builds the gallery Markdown for [pngFileNames] (base names, e.g.
/// `us1-landing-empty.png`), grouped by US in ascending order, with an
/// "Other" group last for anything that doesn't match a known US prefix.
/// Pure and file-system free, so it's unit-testable without real images.
String buildGalleryMarkdown(List<String> pngFileNames) {
  final byGroup = <String, List<String>>{};
  for (final name in pngFileNames) {
    final match = _groupPrefix.firstMatch(name);
    final group = match != null && _groupTitles.containsKey(match.group(1))
        ? match.group(1)!
        : 'other';
    byGroup.putIfAbsent(group, () => []).add(name);
  }

  final orderedGroups = byGroup.keys.toList()
    ..sort((a, b) {
      if (a == 'other') return 1;
      if (b == 'other') return -1;
      return a.compareTo(b);
    });

  final buffer = StringBuffer()
    ..writeln('# Syntax Bridge — screenshots')
    ..writeln()
    ..writeln(
      'Generated by `just screenshots` from the widget-test screenshot '
      'suite (`client/flutter/test/screenshots/`). Do not edit by hand — '
      'regenerate instead.',
    )
    ..writeln();

  for (final group in orderedGroups) {
    buffer
      ..writeln('## ${_groupTitles[group] ?? 'Other'}')
      ..writeln();
    for (final name in byGroup[group]!) {
      final caption = _caption(name, group);
      buffer
        ..writeln('**$caption**')
        ..writeln()
        ..writeln('![$caption]($name)')
        ..writeln();
    }
  }

  return buffer.toString();
}

String _caption(String pngFileName, String group) {
  final stem = pngFileName.replaceAll(RegExp(r'\.png$'), '');
  final withoutGroup = group == 'other'
      ? stem
      : stem.replaceFirst(RegExp('^$group-'), '');
  final words = withoutGroup
      .split('-')
      .where((word) => word.isNotEmpty)
      .toList();
  if (words.isEmpty) return '';

  return [
    words.first[0].toUpperCase() + words.first.substring(1),
    ...words.skip(1),
  ].join(' ');
}
